export const MARKET_MAX_LEVERAGE: Record<string, number> = {
  'SOL-PERP': 20,
  'BTC-PERP': 20,
  'ETH-PERP': 20,
  'APT-PERP': 20,
  'ARB-PERP': 20,
  'AVAX-PERP': 20,
  'BNB-PERP': 20,
  'DOGE-PERP': 20,
  'LINK-PERP': 20,
  'OP-PERP': 20,
  'POL-PERP': 20,
  'SUI-PERP': 20,
  'XRP-PERP': 20,
  'LTC-PERP': 10,
  'BCH-PERP': 10,
  'DOT-PERP': 10,
  'ATOM-PERP': 10,
  'NEAR-PERP': 10,
  'FTM-PERP': 10,
  'INJ-PERP': 10,
  'SEI-PERP': 10,
  'TIA-PERP': 10,
  'JTO-PERP': 10,
  'JUP-PERP': 10,
  'PYTH-PERP': 10,
  'RENDER-PERP': 10,
  'WIF-PERP': 10,
  'BONK-PERP': 10,
  '1MBONK-PERP': 10,
  'PEPE-PERP': 10,
  '1MPEPE-PERP': 10,
  'TRUMP-PERP': 10,
  'HYPE-PERP': 10,
  'TAO-PERP': 10,
  'FARTCOIN-PERP': 5,
  'AI16Z-PERP': 5,
  'PENGU-PERP': 5,
  'MELANIA-PERP': 5,
  'BERA-PERP': 5,
  'KAITO-PERP': 5,
  'IP-PERP': 5,
  'ZEC-PERP': 5,
  'ADA-PERP': 5,
  'PAXG-PERP': 5,
  'PUMP-PERP': 5,
  'GOAT-PERP': 5,
  'MOODENG-PERP': 5,
  'POPCAT-PERP': 5,
  'MEW-PERP': 5,
  '1KMEW-PERP': 5,
  'MOTHER-PERP': 5,
  'W-PERP': 3,
  'TNSR-PERP': 5,
  'DRIFT-PERP': 5,
  'CLOUD-PERP': 5,
  'IO-PERP': 5,
  'ME-PERP': 5,
  'RAY-PERP': 5,
  'PNUT-PERP': 5,
  'MICHI-PERP': 5,
  'FWOG-PERP': 5,
  'TON-PERP': 5,
  'HNT-PERP': 5,
  'RLB-PERP': 5,
  'DYM-PERP': 5,
  'KMNO-PERP': 5,
  'ZEX-PERP': 5,
  '1KWEN-PERP': 5,
  'DBR-PERP': 5,
  'WLD-PERP': 5,
  'ASTER-PERP': 10,
  'XPL-PERP': 5,
  '2Z-PERP': 5,
  'MNT-PERP': 5,
  '1KPUMP-PERP': 5,
  'MET-PERP': 5,
  '1KMON-PERP': 5,
  'LIT-PERP': 5,
  'LAUNCHCOIN-PERP': 3,
};

const DEFAULT_MAX_LEVERAGE = 20;

export function tickerToDriftMarket(ticker: string): string {
  if (ticker.endsWith('-PERP')) return ticker.toUpperCase();
  const base = ticker.split('/')[0].toUpperCase();
  return `${base}-PERP`;
}

export function getDriftMaxLeverage(ticker: string): number {
  const market = tickerToDriftMarket(ticker);
  return MARKET_MAX_LEVERAGE[market] ?? DEFAULT_MAX_LEVERAGE;
}
