// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/lab-hub-redesign/ControlCenter.tsx": () => import("../components/mockups/lab-hub-redesign/ControlCenter.tsx"),
  "./components/mockups/lab-hub-redesign/Current.tsx": () => import("../components/mockups/lab-hub-redesign/Current.tsx"),
  "./components/mockups/lab-hub-redesign/Guided.tsx": () => import("../components/mockups/lab-hub-redesign/Guided.tsx"),
  "./components/mockups/lab-hub-redesign/Launchpad.tsx": () => import("../components/mockups/lab-hub-redesign/Launchpad.tsx")
};
