// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/wallet-money-hub/AgentBasket.tsx": () => import("../components/mockups/wallet-money-hub/AgentBasket.tsx"),
  "./components/mockups/wallet-money-hub/CleanLedger.tsx": () => import("../components/mockups/wallet-money-hub/CleanLedger.tsx"),
  "./components/mockups/wallet-money-hub/LendingClarity.tsx": () => import("../components/mockups/wallet-money-hub/LendingClarity.tsx"),
  "./components/mockups/wallet-money-hub/LendingClarityCompact.tsx": () => import("../components/mockups/wallet-money-hub/LendingClarityCompact.tsx"),
  "./components/mockups/wallet-money-hub/LendingClarityReworked.tsx": () => import("../components/mockups/wallet-money-hub/LendingClarityReworked.tsx"),
  "./components/mockups/wallet-money-hub/MoneyHub.tsx": () => import("../components/mockups/wallet-money-hub/MoneyHub.tsx"),
  "./components/mockups/wallet-money-hub/OverviewFirst.tsx": () => import("../components/mockups/wallet-money-hub/OverviewFirst.tsx"),
  "./components/mockups/wallet-money-hub/OverviewFlows.tsx": () => import("../components/mockups/wallet-money-hub/OverviewFlows.tsx"),
  "./components/mockups/lab-hub-redesign/ControlCenter.tsx": () => import("../components/mockups/lab-hub-redesign/ControlCenter.tsx"),
  "./components/mockups/lab-hub-redesign/Current.tsx": () => import("../components/mockups/lab-hub-redesign/Current.tsx"),
  "./components/mockups/lab-hub-redesign/Guided.tsx": () => import("../components/mockups/lab-hub-redesign/Guided.tsx"),
  "./components/mockups/lab-hub-redesign/Launchpad.tsx": () => import("../components/mockups/lab-hub-redesign/Launchpad.tsx")
};
